[versions]
annotations = "26.0.1"
vavr = "0.9.2"
futures = "0.3.6"
fury = "0.9.0"
lettuce = "6.5.3.RELEASE"
caffeine = "3.2.0"
jackson = "2.18.2"
gson = "2.12.1"

[libraries]
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
vavr = { module = "io.vavr:vavr", version.ref = "vavr" }
spotify-futures = { module = "com.spotify:completable-futures", version.ref = "futures" }
fury-core = { module = "org.apache.fury:fury-core", version.ref = "fury" }
lettuce-core = { module = "io.lettuce:lettuce-core", version.ref = "lettuce" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }